### ISSUE TITLE
Logo Double Colours Light Dark theme 

### ISSUE THREAD

**Issue by daanh432** [daanh432/proftaak2019#139]
https://prolearner.daanhendriks.nl/courses/COURSEID/completed
en in header

![image](https://user-images.githubusercontent.com/8281824/59588511-0ad42b00-90e8-11e9-80fd-c7ba72caba1d.png)

![image](https://user-images.githubusercontent.com/8281824/59588521-11fb3900-90e8-11e9-9d41-d9ce50801eee.png)

**Comment by StijnLingmont** [comment]
Merge pull request #142 from daanh432/develop-stijn
