### ISSUE TITLE
Responsiveness issue with sign in and register page

### ISSUE THREAD

**Issue by daanh432** [daanh432/proftaak2019#46]
![image](https://user-images.githubusercontent.com/8281824/58314118-214fd500-7e0f-11e9-942d-cdc8bc4b4d15.png)

As you can see there are slight responsiveness issues with the sign in and register page.

**Comment by StijnLingmont** [comment]
Gedeelte gefixt! Moet nog naar gekeken worden!

**Comment by StijnLingmont** [comment]
Merge pull request #67 from daanh432/develop-pim
