### ISSUE TITLE
Elements on courses page overlap

### ISSUE THREAD

**Issue by StijnLingmont** [daanh432/proftaak2019#50]
![image](https://user-images.githubusercontent.com/43636145/58409374-2d869d00-8070-11e9-8c89-dd2be6f3aeab.png)

**Comment by StijnLingmont** [comment]
Merge pull request #68 from daanh432/develop-daan

**Comment by daanh432** [comment]
Wasn't fixed in that @StijnLingmont

**Comment by daanh432** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Overzicht van onderdelen bij een cursus](https://trello.com/c/lmy23sNQ/13-overzicht-van-onderdelen-bij-een-cursus)
