### ISSUE TITLE
Certificate Generation on course completion

### ISSUE THREAD

**Issue by daanh432** [daanh432/proftaak2019#74]

**Comment by daanh432** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Certificaat verkrijgbaar na het afronden van een cursus](https://trello.com/c/w8YUqxUb/14-certificaat-verkrijgbaar-na-het-afronden-van-een-cursus)

**Comment by StijnLingmont** [comment]
Certificate can be generated but not get when end course (because end course is not a feauture yet)
