### ISSUE TITLE
Edit course page unresponsive

### ISSUE THREAD

**Issue by pimmetos** [daanh432/proftaak2019#76]
Edit course page unresponsive:
![image](https://user-images.githubusercontent.com/43149220/58538265-0a392a80-81f5-11e9-9ddc-85b1be020efc.png)

![image](https://user-images.githubusercontent.com/43149220/58538245-fab9e180-81f4-11e9-8e7b-ecee4e1da9cd.png)

![image](https://user-images.githubusercontent.com/43149220/58538211-eaa20200-81f4-11e9-9991-245fc7b53dbd.png)

![image](https://user-images.githubusercontent.com/43149220/58538165-d231e780-81f4-11e9-8da3-1ec4b70450b6.png)

**Comment by daanh432** [comment]
Kun jij wel fixen met goed gebruik van col-X en col-lg-X

**Comment by pimmetos** [comment]
Fixed in pull request: https://github.com/daanh432/proftaak2019/pull/79
