### ISSUE TITLE
Design for Dashboard courses overview

### ISSUE THREAD

**Issue by StijnLingmont** [daanh432/proftaak2019#78]
![image](https://user-images.githubusercontent.com/43636145/58539752-4ae67300-81f8-11e9-827a-f753204e0f62.png)

**Comment by StijnLingmont** [comment]
Merge pull request #79 from daanh432/develop-pim

**Comment by daanh432** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Overzicht van voltooide cursussen](https://trello.com/c/3LRZ6Bu0/11-overzicht-van-voltooide-cursussen)
