### ISSUE TITLE
Feedback geven op course en bekijken feedback als course eigenaar

### ISSUE THREAD

**Issue by daanh432** [daanh432/proftaak2019#85]

**Comment by daanh432** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Feedback mogelijkheid bij cursussen](https://trello.com/c/Pg8JZGth/10-feedback-mogelijkheid-bij-cursussen)

**Comment by daanh432** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Overzicht van voltooide cursussen](https://trello.com/c/3LRZ6Bu0/11-overzicht-van-voltooide-cursussen)

**Comment by StijnLingmont** [comment]
Feedback optie mogelijk

**Comment by daanh432** [comment]
@StijnLingmont dit is een van de laatste groten dingen in het project en dan zijn we klaar 😱 😄 
#hyped XD

**Comment by StijnLingmont** [comment]
Merge pull request #141 from daanh432/develop-stijn
